### ISSUE TITLE
a question about a technical point in your blog 

### ISSUE THREAD

**Issue by Tuo-ZHANG** [CyberSmash/cybersmash.github.io#4]
Hi there, I hope my message is not misplaced but I haven't found a comment section in your blog Reverse Engineering Night Raid so I thought maybe I could post my question here.
Your blog is indeed a fascinating read but there is one part I don't understand, in your blog you have written:

**If we restart, Night Raid we can use the IV name to create a variable name that we can then monitor for changes. In our case, the full command will be IV 191D:205e currentWave.**

Could you tell me how do you get the address 191D:205e? I would really appreciate it if you could offer some clarity on this!

Regards,
Tuo ZHANG

**Comment by CyberSmash** [comment]
This was found by first finding the location of the format string `Assault Wave %d`. That string has a memory address of `0x08d8`. The only question from here is its segment address. We use a scalar search in ghidra to find any references to `0x08d8` and there was only one, at location `16c8:2f37` (but there could have been more). Remember that is the segment address as Ghidra has assigned, not the one that Dosbox will assign. 

From there we can look up at the disassembly to see that the number being printed in the format string is the 3rd parameter and that is the address `0x205e`. Again, we don't know the segment address, but that's the memory address if we find the segment address. 

The good news is that the segment addresses are split between code and data, so once we find one we'll find the other. If I remember correctly the way I identified the segment addresses for code and data was to pause the game (break point) at random intervals and see what the `ds` and `cs` registers were. Those will be the segments for the `data segment` and `code segement`. From there you can find the data by prepending the `ds` register's value to the location such as `0x205e`. It's a cheap trick, but it works.

**Comment by Tuo-ZHANG** [comment]
> This was found by first finding the location of the format string `Assault Wave %d`. That string has a memory address of `0x08d8`. The only question from here is its segment address. We use a scalar search in ghidra to find any references to `0x08d8` and there was only one, at location `16c8:2f37` (but there could have been more). Remember that is the segment address as Ghidra has assigned, not the one that Dosbox will assign.
> 
> From there we can look up at the disassembly to see that the number being printed in the format string is the 3rd parameter and that is the address `0x205e`. Again, we don't know the segment address, but that's the memory address if we find the segment address.
> 
> The good news is that the segment addresses are split between code and data, so once we find one we'll find the other. If I remember correctly the way I identified the segment addresses for code and data was to pause the game (break point) at random intervals and see what the `ds` and `cs` registers were. Those will be the segments for the `data segment` and `code segement`. From there you can find the data by prepending the `ds` register's value to the location such as `0x205e`. It's a cheap trick, but it works.

Thanks for your reply. If I understand correctly, we need to run the game to get the value 0x205e, right? And this value will be the value in AX on line 16c8: 2f3d as shown in the screenshot in your blog:
![image](https://cybersmash.github.io/assets/img/Pasted%20image%2020220601210600.png)
Please correct me if my understanding is faulty.

**Comment by CyberSmash** [comment]
No, we need to run the program to get the `ds` register of `0x191d` . The address of `CurrentWave` will always be `0x205e`, as it's the offset inside of that memory segment. The symbol `CurrentWave` at address `16c8:2f32` in the above screen shot is just an alias in ghidra for the address `XXXX:205e` where `XXXX` is whatever the data segment register is (likely `0x191d` in DOSBox, but ghidra has it loaded at `0x2730`).

**Comment by Tuo-ZHANG** [comment]
> Reverse Engineering Night Raid

**Comment by Tuo-ZHANG** [comment]
> No, we need to run the program to get the `ds` register of `0x191d` . The address of `CurrentWave` will always be `0x205e`, as it's the offset inside of that memory segment. The symbol `CurrentWave` at address `16c8:2f32` in the above screen shot is just an alias in ghidra for the address `XXXX:205e` where `XXXX` is whatever the data segment register is (likely `0x191d` in DOSBox, but ghidra has it loaded at `0x2730`).

Oh, I just noticed that 20 5e was pushed to AX on the first line in the screenshot. Now I understand. Thank you for your clarification!
